version: 2

models:
  - name: dim_employee
    columns:
      - name: employee_id
        tests:
          - not_null
          - unique

      - name: valid_from
        tests:
          - not_null

    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - employee_id
              - valid_from
  - name: dim_employee_scd2
    description: "SCD2 employee dimension built from dbt snapshot snap_employees."
    columns:
      - name: employee_id
        tests:
          - not_null
      - name: valid_from
        tests:
          - not_null
