version: 2

models:
  - name: dim_employee
    description: "Employee dimension (SCD-style). One row per employee version."
    config:
      contract:
        enforced: true
    columns:
      - name: employee_id
        description: "Natural employee identifier."
        data_type: INT64
        tests:
          - not_null
      - name: valid_from
        description: "Start timestamp for this employee version."
        data_type: TIMESTAMP
        tests:
          - not_null

    tests:
      - unique_combo:
          combination_of_columns: ["employee_id", "valid_from"]

  - name: fct_funnel_conversion_daily
    description: "Daily funnel stage-to-next-stage conversion rate based on candidate stage events."
    columns:
      - name: event_date
        description: "Date of the funnel events."
        tests:
          - not_null

      - name: from_stage
        description: "Stage the candidate is converting from (e.g., Applied)."
        tests:
          - not_null

      - name: to_stage
        description: "Next stage (e.g., Screen)."
        tests:
          - not_null

      - name: entered_candidates
        description: "Number of distinct candidates who entered the stage on that day."
        tests:
          - not_null

      - name: progressed_candidates
        description: "Number of distinct candidates who progressed to next stage on that day."
        tests:
          - not_null

